---
- name: Crear usuario huamani en el servidor FTP
  hosts: servidor_ftp
  become: yes
  
  tasks:
    - name: Crear usuario huamani
      user:
        name: huamani
        state: present
      become: yes

    - name: Asignar contraseña al usuario huamani
      user:
        name: huamani
        password: "{{ 'contraseña_encriptada' | password_hash('sha512') }}"
      become: yes
